insee:
  cog:
    communes:
      url: https://www.insee.fr/fr/statistiques/fichier/5057840/commune2021-csv.zip
      date: 01/2021
      hash: 67a88da9061609c861b20aa853f5480d1fcdc8431e3911ae6c6c03cc925febd7
      extraire: csv
    cantons:
      url: https://www.insee.fr/fr/statistiques/fichier/5057840/canton2021-csv.zip
      date: 01/2021
      hash: 7884448d9a36f1d79ad4a2d35bbdb26571a3e43da977c733eac5bffd22f783a6
      extraire: csv
    arrondissements:
      url: https://www.insee.fr/fr/statistiques/fichier/5057840/arrondissement2021-csv.zip
      date: 01/2021
      hash: a49c3f0cdef3532b1e5a51b5bbfba31e56374dbdf53a6726a224e115f5b9dfb8
      extraire: csv
    departements:
      url: https://www.insee.fr/fr/statistiques/fichier/5057840/departement2021-csv.zip
      date: 01/2021
      hash: 55b0999478a2992566743dcd3560ed4be4dda01349574240fce1c37fa6fd0587
      extraire: csv
    regions:
      url: https://www.insee.fr/fr/statistiques/fichier/5057840/region2021-csv.zip
      date: 01/2021
      hash: 5fc418c45b2e3faea6ae91540d4da6baaec125dabf18085924cc31b33c3b01f5
      extraire: csv
    evenements:
      url: https://www.insee.fr/fr/statistiques/fichier/5057840/mvtcommune2021-csv.zip
      date: 01/2021
      hash: 7e792f561ce2e8963e84a37456d723db9754ec22217d1f00ee4f723ccb3c634f
      extraire: csv

  population:
    url: https://www.insee.fr/fr/statistiques/fichier/4265429/ensemble.zip
    date: 01/01/2019
    hash: 7c12879f5812772c29ab32f40310ef20ee16082c96f34b64152bb83cb1359307
    extraire:
      - Communes.csv
      - Communes_associees_ou_deleguees.csv

  intercommunalite:
    epci:
      url: https://www.insee.fr/fr/statistiques/fichier/2510634/Intercommunalite_Metropole_au_01-01-2021.zip
      date: 01/2021
      hash: 3b9b9c764cab9359f7bca7d05fc0b15e91b205ab837f46e2b03f50a7af367f1d
      extraire: xlsx

ign:
  admin-express:
    version-cog:
      url: ftp://Admin_Express_ext:Dahnoh0eigheeFok@ftp3.ign.fr/ADMIN-EXPRESS-COG_3-0__SHP__FRA_L93_2021-05-19.7z
      date: 19/05/2021
      hash: 32665c035409792ce178e270c9fd5ad5aa1d9e52ea0c0d7817c7b3c77a9e8034
      extraire: False


interieur:
  rne:
    municipaux:
      url: https://static.data.gouv.fr/resources/repertoire-national-des-elus-1/20210422-103240/rne-cm.csv
      date: 22/04/2021
      hash: a2ab20e21fc2295bb085aaf2a70e0f45fe5d0be482878ed43f4a86040dae5811
    epci:
      url: https://static.data.gouv.fr/resources/repertoire-national-des-elus-1/20210422-103340/rne-epci.csv
      date: 02/12/2020
      hash: a325d77b8d63fec3f5afc030daf8730fe0240551971444cadaa9a4dbe654063d
  resultats_electoraux:
    presidentielles:
      2017:
        tour1:
          url: https://www.data.gouv.fr/s/resources/election-presidentielle-des-23-avril-et-7-mai-2017-resultats-definitifs-du-1er-tour-par-bureaux-de-vote/20170427-100955/PR17_BVot_T1_FE.txt
          date: 04/2017
          hash: 1eb1e4358a8af59ebc86ff7e0e4a2ee175f6cf516e4598cd955193064fc91e6a
        tour2:
          url: https://www.data.gouv.fr/s/resources/election-presidentielle-des-23-avril-et-7-mai-2017-resultats-definitifs-du-2nd-tour-par-bureaux-de-vote/20170511-093541/PR17_BVot_T2_FE.txt
          date: 05/2017
          hash: 2b6137b64957b9bfff24436cf859aad15e8b155b837b182eebff71c21fc82798
    legislatives:
      2017:
        tour1:
          url: https://www.data.gouv.fr/s/resources/elections-legislatives-des-11-et-18-juin-2017-resultats-par-bureaux-de-vote-du-1er-tour/20170613-100441/Leg_2017_Resultats_BVT_T1_c.txt
          date: 06/2017
          hash: f0e0d5149af2a52b843712329889f607efd589dd4836f0ec1334eb8b164e5fdb
        tour2:
          url: https://www.data.gouv.fr/s/resources/elections-legislatives-des-11-et-18-juin-2017-resultats-du-2nd-tour-par-bureaux-de-vote/20170620-094954/Leg_2017_Resultats_BVT_T2_c.txt
          date: 06/2017
          hash: 2d898b6bebcc401b79fe3ebbc0deb37d5dcc32c11ac3f5e8be0b0f006ee9eb8e
    europeennes:
      2019:
        url: https://static.data.gouv.fr/resources/resultats-des-elections-europeennes-2019/20190531-144007/resultats-definitifs-par-bureau-de-vote.txt
        date: 31/05/2019
        hash: a54a77872089f893145b9bad4d3d8479220bf60efa0fc3d0a81f54ede4d12208
      2014:
        url: https://www.data.gouv.fr/s/resources/elections-europeennes-2014-resultats-par-bureaux-de-vote/20150925-112120/ER14_BVOT.txt
        date: 25/09/2015
        hash: af1840b437db8a154f5b286c18a45d7534238ab8b9e73b7e843d8655d1b22e32
    municipales:
      2020:
        tour1:
          url: https://static.data.gouv.fr/resources/elections-municipales-2020-resultats/20200525-133745/2020-05-18-resultats-par-niveau-burvot-t1-france-entiere.txt
          date: 18/05/2020
          hash: ab2c17eccd3fc0358db8007a7faceb3697e51af847c2aada8018669a4e167071
          delimiter: "\t"
          corrected: ".csv"
        tour2:
          url: https://static.data.gouv.fr/resources/municipales-2020-resultats-2nd-tour/20200629-192438/resultats-par-niveau-burvot-t2-france-entiere.txt
          date: 30/06/2020
          hash: 07e1c3e1a547094e16250d3b659a2de19ea57e377ef0b586d6dbc6df27609c45
      2014:
        url: https://www.data.gouv.fr/s/resources/elections-municipales-2014-resultats-par-bureaux-de-vote/20150925-122128/MN14_Bvot_T1T2.txt
        date: 25/09/2015
        hash: fe8ae42befb8e006dce1d959bee237449c9f39506c940e68c9b49a20f4363570
    regionales:
      2021:
        tour1:
          url: https://static.data.gouv.fr/resources/regionales-2021-resultats-du-1er-tour/20210622-130530/resultats-par-niveau-bv-t1-france-entiere-2021-06-22-11h36.txt
          date: 22/06/2021
          hash: 877493d2a80fa6f3b417490f9c069844ca714681e8d57bd0c52ff93d9a47086c
        tour2:
          url: https://static.data.gouv.fr/resources/elections-regionales-2021-resultats-2eme-tour/20210701-120503/resultats-par-niveau-burvot-t2-france-entiere-2021-06-30-13h33.txt
          date: 01/07/2021
          hash: 9f7cea21779650c5f788b0fb2a0d439aef5ee3a0c096b99404d923ca88bca594
    departementales:
      2021:
        tour1:
          url: https://static.data.gouv.fr/resources/elections-departementales-2021-resultats-du-1er-tour/20210622-165822/resultats-par-niveau-burvot-t1-france-entiere.txt
          hash: 7b135ed4a6500e6aa16e63af3c5076aa8d8159cf1aa90b742a5dc0c12dd1dce5
          date: 22/06/2021
        tour2:
          url: https://static.data.gouv.fr/resources/elections-departementales-2021-resultats-du-2eme-tour/20210701-120141/resultats-par-niveau-burvot-t2-france-entiere-2021-06-30.txt
          hash: 4af3b66cf3e81de036954e473baf97f37fb24daa95020224918b4470a4e5fde7
          date: 01/07/2021

laposte:
  codes_postaux:
    url: https://datanova.laposte.fr/explore/dataset/laposte_hexasmal/download/?format=csv&timezone=Europe/Berlin&lang=fr&use_labels_for_header=true&csv_separator=%2C
    extension: .csv
    hash: f0667bfb6f4b942321cd098936d22f2b130d05f6d5fdecc64efeb66d8aa4e4be

premier_ministre:
  annuaire_administration:
    url: http://lecomarquage.service-public.fr/donnees_locales_v2/all_latest.tar.bz2
    extension: .tar.bz2
    hash: 09ee542c0413c04cffcda06b3ef245cdbdb00afe5e0213db9de8705a4f4e29d7
    extraire: no

conseil_constitutionnel:
  parrainages2017:
    url: https://presidentielle2017.conseil-constitutionnel.fr/wp-content/uploads/2017/03/parrainagestotal.csv
    hash: 8af6c3fe6f2c57ed6751c9a1daa36b26ae873578601ada0aa5483833ef4c8371
