insee:
  cog:
    url: https://www.insee.fr/fr/statistiques/fichier/7766585/cog_ensemble_2024_csv.zip
    date: 17/02/2023
    hash: 9842beab5eeb292febd4ad0dc46a3dd05b929794a42357447426511739e9abff
    extraire:
      - v_canton_2024.csv
      - v_commune_2024.csv
      - v_ctcd_2024.csv
      - v_departement_2024.csv
      - v_mvt_commune_2024.csv
      - v_region_2024.csv

  iris:
    contours:
      url: https://data.geopf.fr/telechargement/download/CONTOURS-IRIS/CONTOURS-IRIS_2-1__SHP__FRA_2021-01-01/CONTOURS-IRIS_2-1__SHP__FRA_2021-01-01.7z
      date: 01/01/2021
      hash: f0bf22ce2335f83fcf2ad4692087ccda5a57db41d2c33f61fba7928087fcfb49
      extraire: []

  population:
    url: https://www.insee.fr/fr/statistiques/fichier/4265429/ensemble.zip
    date: 01/01/2019
    hash: 7c12879f5812772c29ab32f40310ef20ee16082c96f34b64152bb83cb1359307
    extraire:
      - Communes.csv
      - Communes_associees_ou_deleguees.csv

  elire:
    bureaux_vote:
      url: https://www.data.gouv.fr/fr/datasets/r/6faacf36-1897-43f5-bf39-af8b41a15d26
      date: 27/06/2023
      hash: 48047ca16b3a539bf600a05b09eb524c183e4acabe4ed8ca476be5a31f1f2106
      extension: .parquet

  intercommunalite:
    epci:
      url: https://www.insee.fr/fr/statistiques/fichier/2510634/Intercommunalite_Metropole_au_01-01-2023.zip
      date: 01/2023
      hash: 65e228464d18b45249f642690848b687a1bbc2b5399e18475b938275b475d868
      extraire: xlsx

ign:
  admin-express:
    version-cog:
      url: https://data.geopf.fr/telechargement/download/ADMIN-EXPRESS-COG/ADMIN-EXPRESS-COG_3-2__SHP_WGS84G_FRA_2024-02-22/ADMIN-EXPRESS-COG_3-2__SHP_WGS84G_FRA_2024-02-22.7z
      date: 22/02/2024
      hash:  7ec91626a7c4acda765caa41fe3093bece4d1a03b8e0e6f2d0cdbd3a995ee055
      extraire: []


interieur:
  rne:
    municipaux:
      url: https://www.data.gouv.fr/fr/datasets/r/d5f400de-ae3f-4966-8cb6-a85c70c6c24a
      extension: .csv
      date: 16/12/2022
      hash: 985f347f2b780cb9d75be898bccbe51d06d8ba8be1c78786946fad1c085c0532
    epci:
      url: https://www.data.gouv.fr/fr/datasets/r/41d95d7d-b172-4636-ac44-32656367cdc7
      extension: .csv
      date: 16/12/2022
      hash: d9681ed31dcd4c4087565a0019d70cf09e8cfb51dcda986d7c365f9c994cb195
    departementaux:
      url: https://www.data.gouv.fr/fr/datasets/r/601ef073-d986-4582-8e1a-ed14dc857fba
      extension: .csv
      date: 16/12/2022
      hash: de28682d0232a9b23255e7f9f4188289be22a06a672e06a496745033ae45f5b5
    regionaux:
      url: https://www.data.gouv.fr/fr/datasets/r/430e13f9-834b-4411-a1a8-da0b4b6e715c
      extension: .csv
      date: 16/12/2022
      hash: 11d7b97a012cec7400a7d50e854eea3af2b0e9ad3981087b31c7c6cab96dda80
    europeens:
      url: https://www.data.gouv.fr/fr/datasets/r/70957bb0-f19f-40c5-b97b-90b3d4d71f9e
      extension: .csv
      date: 16/12/2022
      hash: 94945bc85d8d2defebe305e0586e3ab35d1f2601ffdf6885688f9325981d0d77
    uniques:
      url: https://www.data.gouv.fr/fr/datasets/r/a595be27-cfab-4810-b9d4-22e193bffe35
      extension: .csv
      date: 16/12/2022
      hash: 617c90adec800c0446060d57871e5e9f1a3d44a074506497c2f78cde838c286b

  resultats_electoraux:
    presidentielles:
      2012:
        url: https://www.data.gouv.fr/fr/datasets/r/206b1668-2b31-46da-b957-9857f94fe85c
        date: 09/2015
        extension: .txt
        hash: baf999ed0d5aee3cfa3192e152f34db4b0e77af72bad18af4853c4b7b958448e
        encoding: latin1
      2017:
        tour1:
          url: https://www.data.gouv.fr/s/resources/election-presidentielle-des-23-avril-et-7-mai-2017-resultats-definitifs-du-1er-tour-par-bureaux-de-vote/20170427-100955/PR17_BVot_T1_FE.txt
          date: 04/2017
          hash: 1eb1e4358a8af59ebc86ff7e0e4a2ee175f6cf516e4598cd955193064fc91e6a
          encoding: latin1
        tour2:
          url: https://www.data.gouv.fr/s/resources/election-presidentielle-des-23-avril-et-7-mai-2017-resultats-definitifs-du-2nd-tour-par-bureaux-de-vote/20170511-093541/PR17_BVot_T2_FE.txt
          date: 05/2017
          hash: 2b6137b64957b9bfff24436cf859aad15e8b155b837b182eebff71c21fc82798
          encoding: latin1
      2022:
        tour1:
          url: https://www.data.gouv.fr/fr/datasets/r/79b5cac4-4957-486b-bbda-322d80868224
          extension: .txt
          date: 04/2022
          hash: d878f33c4c1488188af0ca0eee9ff5a3116ea88c44979a1538ff43c663831624
          encoding: latin1
        tour2:
          url: https://www.data.gouv.fr/fr/datasets/r/4dfd05a9-094e-4043-8a19-43b6b6bbe086
          extension: .txt
          date: 04/2022
          hash: c2ead8aaa3501db95bc887ef949504c914b66d81b2d46313bbfcc5fdeea0bff3
          encoding: latin1
    legislatives:
      2012:
          url: https://www.data.gouv.fr/fr/datasets/r/32981cf5-2560-48c7-a355-1acdf33bd504
          date: 09/2015
          extension: .txt
          hash: 12dc6f0b56ea1cbe799b6ca5c01cbd028d7820b8ed64c7c29347cd11a6fca60f
          encoding: latin1
      2017:
        tour1:
          url: https://www.data.gouv.fr/s/resources/elections-legislatives-des-11-et-18-juin-2017-resultats-par-bureaux-de-vote-du-1er-tour/20170613-100441/Leg_2017_Resultats_BVT_T1_c.txt
          date: 06/2017
          hash: f0e0d5149af2a52b843712329889f607efd589dd4836f0ec1334eb8b164e5fdb
          encoding: latin1
        tour2:
          url: https://www.data.gouv.fr/s/resources/elections-legislatives-des-11-et-18-juin-2017-resultats-du-2nd-tour-par-bureaux-de-vote/20170620-094954/Leg_2017_Resultats_BVT_T2_c.txt
          date: 06/2017
          hash: 2d898b6bebcc401b79fe3ebbc0deb37d5dcc32c11ac3f5e8be0b0f006ee9eb8e
          encoding: latin1
      2022:
        tour1:
          url: https://www.data.gouv.fr/fr/datasets/r/2632e5e7-8deb-49f7-bebf-e6ea0ec3d253
          date: 13/06/2022
          extension: .txt
          hash: 237c89b199d04137350358a6fd0ce81d8189e10ff1ce5c7e1616eef78266b84f
          encoding: latin1
        tour2:
          url: https://www.data.gouv.fr/fr/datasets/r/cada247a-6528-44e7-8308-30c0c335a4b2
          date: 20/06/2022
          extension: .txt
          hash: 6fea869e277c871fa862428fc718c8b2dc8f08c96a3db1b7d28074c064271993
          encoding: latin1
    europeennes:
      2024:
        url: https://static.data.gouv.fr/resources/resultats-des-elections-europeennes-du-9-juin-2024/20240613-154804/resultats-definitifs-par-bureau-de-vote.csv
        date: 13/06/2024
        hash: 89e879541dcb7e77f79c38b2e1976ba401f7b9891dd98f2569e53d06245c8510
      2019:
        url: https://static.data.gouv.fr/resources/resultats-des-elections-europeennes-2019/20190531-144007/resultats-definitifs-par-bureau-de-vote.txt
        date: 31/05/2019
        hash: a54a77872089f893145b9bad4d3d8479220bf60efa0fc3d0a81f54ede4d12208
        encoding: latin1
      2014:
        url: https://www.data.gouv.fr/s/resources/elections-europeennes-2014-resultats-par-bureaux-de-vote/20150925-112120/ER14_BVOT.txt
        date: 25/09/2015
        hash: af1840b437db8a154f5b286c18a45d7534238ab8b9e73b7e843d8655d1b22e32
        encoding: latin1
    municipales:
      2020:
        tour1:
          url: https://static.data.gouv.fr/resources/elections-municipales-2020-resultats/20200525-133745/2020-05-18-resultats-par-niveau-burvot-t1-france-entiere.txt
          date: 18/05/2020
          hash: ab2c17eccd3fc0358db8007a7faceb3697e51af847c2aada8018669a4e167071
          delimiter: "\t"
          corrected: ".csv"
          encoding: latin1
        tour2:
          url: https://static.data.gouv.fr/resources/municipales-2020-resultats-2nd-tour/20200629-192438/resultats-par-niveau-burvot-t2-france-entiere.txt
          date: 30/06/2020
          hash: 07e1c3e1a547094e16250d3b659a2de19ea57e377ef0b586d6dbc6df27609c45
          encoding: latin1
      2014:
        url: https://www.data.gouv.fr/s/resources/elections-municipales-2014-resultats-par-bureaux-de-vote/20150925-122128/MN14_Bvot_T1T2.txt
        date: 25/09/2015
        hash: fe8ae42befb8e006dce1d959bee237449c9f39506c940e68c9b49a20f4363570
        encoding: latin1
    regionales:
      2021:
        tour1:
          url: https://static.data.gouv.fr/resources/elections-regionales-2021-resultats-du-1er-tour-1/20210713-100715/reg-resultats-par-niveau-burvot-t1-france-entiere-2021-07-12-18h44.txt
          date: 22/06/2021
          hash: 71a3c1e21a99452a7df5b1be6ba2677fae47ead876322a1d613c3e90648199bf
          encoding: latin1
        tour2:
          url: https://static.data.gouv.fr/resources/elections-regionales-2021-resultats-du-2eme-tour/20210713-100020/regresultats-par-niveau-burvot-t2-france-entiere-2021-07-12-09h06.txt
          date: 01/07/2021
          hash: 9f7cea21779650c5f788b0fb2a0d439aef5ee3a0c096b99404d923ca88bca594
          encoding: latin1
    departementales:
      2021:
        tour1:
          url: https://static.data.gouv.fr/resources/elections-departementales-2021-resultats-du-1er-tour/20210622-165822/resultats-par-niveau-burvot-t1-france-entiere.txt
          hash: 7b135ed4a6500e6aa16e63af3c5076aa8d8159cf1aa90b742a5dc0c12dd1dce5
          date: 22/06/2021
          encoding: latin1
        tour2:
          url: https://static.data.gouv.fr/resources/elections-departementales-2021-resultats-du-2eme-tour/20210713-101218/dep-resultats-par-niveau-burvot-t2-france-entiere-2021-07-12-09h49.txt
          hash: 4e0f4f658b5ce04b9c20b4dc38c46eda3fdc74407b0f244f33fae29bc799eac8
          date: 01/07/2021
          encoding: latin1
    referendums:
      2005:
        url: https://www.data.gouv.fr/fr/datasets/r/8b1f3e0e-001f-414c-9bf0-7b5a9219e26a
        date: 09/2015
        hash: c93bb1e0711db91d0d1e25322912ba6c7eb3df32d11bc4df63e6ac3cf1727911
        extension: .txt
        corrected: .csv
        encoding: latin1

laposte:
  codes_postaux:
    url: https://datanova.laposte.fr/data-fair/api/v1/datasets/laposte-hexasmal/data-files/019HexaSmal.csv
    extension: .csv
    hash: 2f46857353904e4e6091a121abbe54dbbf1eaf502f7e691c34e33a0e16e3306b


premier_ministre:
  annuaire_administration:
    url: https://www.data.gouv.fr/fr/datasets/r/73302880-e4df-4d4c-8676-1a61bb997f3d
    extension: .tar.bz2
    hash: ef4e0f1a805d11a6d0cb0a679c1aff5007f3c5357a1e5920a6aaea1de79751d8
    extraire: []


conseil_constitutionnel:
  parrainages2017:
    url: https://presidentielle2017.conseil-constitutionnel.fr/wp-content/uploads/2017/03/parrainagestotal.csv
    hash: 8af6c3fe6f2c57ed6751c9a1daa36b26ae873578601ada0aa5483833ef4c8371


assemblee_nationale:
  deputes:
    url: http://data.assemblee-nationale.fr/static/openData/repository/16/amo/deputes_actifs_mandats_actifs_organes/AMO10_deputes_actifs_mandats_actifs_organes.json.zip
    hash: 0a01f560df6ef4c83da76e5d76f0e1ed6a5b17d73bcad93656310a7d7669875d


sciences_po:
  contours_circonscriptions_legislatives:
    url: https://static.data.gouv.fr/resources/carte-des-circonscriptions-legislatives-2012-et-2017/20170721-135742/france-circonscriptions-legislatives-2012.json
    hash: 28c4291fdff57bb2b0c511c6fb514929d1ec650677ae25ff9f21a375cfe67515
    date: 21/07/2021


lemonde:
  nuances_premier_tour_legislatives2022:
    url: https://assets-decodeurs.lemonde.fr/decodeurs/elections_2022/legislatives/tour1/candidats_legislatives_lemonde.csv
    hash: f17ee219be6cb5111eab360b449326b65d28f8e4add5022fedce3e7aa64a1c16
    date: 01/06/2022
