# Generated by Django 3.0.4 on 2020-03-27 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="code_departement",
            field=models.CharField(
                editable=False, max_length=5, verbose_name="Code du département"
            ),
        ),
        migrations.AlterField(
            model_name="commune",
            name="commune_parent",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="composants",
                related_query_name="composant",
                to="data_france.Commune",
            ),
        ),
        migrations.AlterField(
            model_name="commune",
            name="epci",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communes",
                related_query_name="commune",
                to="data_france.EPCI",
            ),
        ),
        migrations.AlterField(
            model_name="commune",
            name="population_cap",
            field=models.PositiveIntegerField(
                editable=False, null=True, verbose_name="Population comptée à part"
            ),
        ),
        migrations.AlterField(
            model_name="commune",
            name="population_municipale",
            field=models.PositiveIntegerField(
                editable=False, null=True, verbose_name="Population municipale"
            ),
        ),
    ]
