# Generated by Django 3.0.4 on 2020-03-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0004_auto_20200327_0531"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commune",
            options={
                "ordering": ("code", "nom", "type"),
                "verbose_name": "Commune",
                "verbose_name_plural": "Communes",
            },
        ),
        migrations.AlterModelOptions(
            name="epci",
            options={
                "ordering": ("code", "nom"),
                "verbose_name": "EPCI",
                "verbose_name_plural": "EPCIs",
            },
        ),
    ]
