# Generated by Django 3.0.5 on 2020-04-08 11:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0007_ajout_departements_regions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="epci",
            options={
                "ordering": ("code", "nom"),
                "verbose_name": "EPCI",
                "verbose_name_plural": "EPCI",
            },
        ),
        migrations.AlterField(
            model_name="commune",
            name="departement",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="communes",
                related_query_name="commune",
                to="data_france.Departement",
                verbose_name="Département",
            ),
        ),
        migrations.AlterField(
            model_name="commune",
            name="epci",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communes",
                related_query_name="commune",
                to="data_france.EPCI",
                verbose_name="EPCI",
            ),
        ),
        migrations.AlterField(
            model_name="commune",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True, null=True, srid=4326, verbose_name="Géométrie"
            ),
        ),
        migrations.AlterField(
            model_name="departement",
            name="chef_lieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                related_query_name="chef_lieu_de",
                to="data_france.Commune",
                verbose_name="Chef-lieu",
            ),
        ),
        migrations.AlterField(
            model_name="departement",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True, null=True, srid=4326, verbose_name="Géométrie"
            ),
        ),
        migrations.AlterField(
            model_name="departement",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departements",
                related_query_name="departement",
                to="data_france.Region",
                verbose_name="Région",
            ),
        ),
        migrations.AlterField(
            model_name="epci",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True, null=True, srid=4326, verbose_name="Géométrie"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="chef_lieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                related_query_name="chef_lieu_de",
                to="data_france.Commune",
                verbose_name="Chef-lieu",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True, null=True, srid=4326, verbose_name="Géométrie"
            ),
        ),
    ]
