# Generated by Django 3.0.5 on 2020-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0008_ajouts_verbose_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="code",
            field=models.CharField(
                editable=False, max_length=10, verbose_name="Code INSEE"
            ),
        ),
        migrations.AlterField(
            model_name="departement",
            name="code",
            field=models.CharField(
                editable=False, max_length=3, unique=True, verbose_name="Code INSEE"
            ),
        ),
        migrations.AlterField(
            model_name="epci",
            name="code",
            field=models.CharField(
                editable=False, max_length=10, unique=True, verbose_name="Code SIREN"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="code",
            field=models.CharField(
                editable=False, max_length=3, unique=True, verbose_name="Code INSEE"
            ),
        ),
        migrations.CreateModel(
            name="CodePostal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        max_length=5,
                        unique=True,
                        verbose_name="Code postal",
                    ),
                ),
                (
                    "communes",
                    models.ManyToManyField(
                        related_name="codes_postaux",
                        related_query_name="codes_postaux",
                        to="data_france.Commune",
                        verbose_name="Communes dans ce code postal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Code postal",
                "verbose_name_plural": "Codes postaux",
                "ordering": ("code",),
            },
        ),
    ]
