# Generated by Django 3.0.5 on 2020-04-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0010_ameliore_recherche"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="type",
            field=models.CharField(
                choices=[
                    ("COM", "Commune"),
                    ("COMD", "Commune déléguée"),
                    ("COMA", "Commune associée"),
                    ("ARM", "Arrondissement de Paris/Lyon/Marseille"),
                    ("SRM", "Secteur électoral de Paris/Lyon/Marseille"),
                ],
                default="COM",
                editable=False,
                max_length=4,
                verbose_name="Type de commune",
            ),
        ),
    ]
