# Generated by Django 3.0.5 on 2021-01-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0013_cantons"),
    ]

    operations = [
        migrations.CreateModel(
            name="EluMunicipal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        editable=False, max_length=200, verbose_name="Nom de famille"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        verbose_name="Prénom",
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Feminin")],
                        max_length=1,
                        verbose_name="Sexe à l'état civil",
                    ),
                ),
                (
                    "date_naissance",
                    models.DateField(editable=False, verbose_name="Date de naissance"),
                ),
                (
                    "profession",
                    models.SmallIntegerField(
                        editable=False, null=True, verbose_name="Profession"
                    ),
                ),
                (
                    "date_debut_mandat",
                    models.DateField(
                        editable=False, verbose_name="Date de début du mandat"
                    ),
                ),
                (
                    "fonction",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        verbose_name="Fonction",
                    ),
                ),
                (
                    "date_debut_fonction",
                    models.DateField(
                        null=True, verbose_name="Date de début de la fonction"
                    ),
                ),
                (
                    "nationalite",
                    models.CharField(
                        editable=False, max_length=30, verbose_name="Nationalité"
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="elus",
                        related_query_name="elu",
                        to="data_france.Commune",
                    ),
                ),
            ],
        ),
    ]
