# Generated by Django 3.0.5 on 2021-01-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0015_recherche_elus_municipaux"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectivitedepartementale",
            name="type_nom",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pas d'article, commence par une consonne (sauf H muet)"),
                    (1, "Pas d'article, commence par une voyelle (ou H muet)"),
                    (2, "Article = LE"),
                    (3, "Article = LA"),
                    (4, "Article = LES"),
                    (5, "Article = L'"),
                    (6, "Article = AUX"),
                    (7, "Article = LAS"),
                    (8, "Article = LOS"),
                ],
                default=0,
                editable=False,
                verbose_name="Type de nom",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collectiviteregionale",
            name="type_nom",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pas d'article, commence par une consonne (sauf H muet)"),
                    (1, "Pas d'article, commence par une voyelle (ou H muet)"),
                    (2, "Article = LE"),
                    (3, "Article = LA"),
                    (4, "Article = LES"),
                    (5, "Article = L'"),
                    (6, "Article = AUX"),
                    (7, "Article = LAS"),
                    (8, "Article = LOS"),
                ],
                default=0,
                editable=False,
                verbose_name="Type de nom",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="canton",
            name="type_nom",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pas d'article, commence par une consonne (sauf H muet)"),
                    (1, "Pas d'article, commence par une voyelle (ou H muet)"),
                    (2, "Article = LE"),
                    (3, "Article = LA"),
                    (4, "Article = LES"),
                    (5, "Article = L'"),
                    (6, "Article = AUX"),
                    (7, "Article = LAS"),
                    (8, "Article = LOS"),
                ],
                editable=False,
                verbose_name="Type de nom",
            ),
        ),
        migrations.AlterField(
            model_name="commune",
            name="type_nom",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pas d'article, commence par une consonne (sauf H muet)"),
                    (1, "Pas d'article, commence par une voyelle (ou H muet)"),
                    (2, "Article = LE"),
                    (3, "Article = LA"),
                    (4, "Article = LES"),
                    (5, "Article = L'"),
                    (6, "Article = AUX"),
                    (7, "Article = LAS"),
                    (8, "Article = LOS"),
                ],
                editable=False,
                verbose_name="Type de nom",
            ),
        ),
        migrations.AlterField(
            model_name="departement",
            name="type_nom",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pas d'article, commence par une consonne (sauf H muet)"),
                    (1, "Pas d'article, commence par une voyelle (ou H muet)"),
                    (2, "Article = LE"),
                    (3, "Article = LA"),
                    (4, "Article = LES"),
                    (5, "Article = L'"),
                    (6, "Article = AUX"),
                    (7, "Article = LAS"),
                    (8, "Article = LOS"),
                ],
                editable=False,
                verbose_name="Type de nom",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="type_nom",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Pas d'article, commence par une consonne (sauf H muet)"),
                    (1, "Pas d'article, commence par une voyelle (ou H muet)"),
                    (2, "Article = LE"),
                    (3, "Article = LA"),
                    (4, "Article = LES"),
                    (5, "Article = L'"),
                    (6, "Article = AUX"),
                    (7, "Article = LAS"),
                    (8, "Article = LOS"),
                ],
                editable=False,
                verbose_name="Type de nom",
            ),
        ),
    ]
