# Generated by Django 3.1.5 on 2021-02-02 10:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0016_auto_20210122_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="mairie_accessibilite",
            field=models.CharField(
                choices=[
                    ("ACC", "Accessible"),
                    ("DEM", "Sur demande préalable"),
                    ("NAC", "Non accessible"),
                ],
                default="NAC",
                max_length=3,
                verbose_name="Accessibilité de la mairie",
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="mairie_accessibilite_details",
            field=models.TextField(
                blank=True, verbose_name="Accessibilité de la mairie (détails)",
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="mairie_adresse",
            field=models.TextField(blank=True, verbose_name="Adresse de la mairie"),
        ),
        migrations.AddField(
            model_name="commune",
            name="mairie_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email de la mairie"
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="mairie_horaires",
            field=models.JSONField(default=list, verbose_name="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name="commune",
            name="mairie_localisation",
            field=django.contrib.gis.db.models.fields.PointField(
                null=True,
                srid=4326,
                verbose_name="Localisation de la mairie",
                geography=True,
            ),
        ),
        migrations.AddField(
            model_name="commune",
            name="mairie_site",
            field=models.URLField(blank=True, verbose_name="Site web de la mairie"),
        ),
        migrations.AddField(
            model_name="commune",
            name="mairie_telephone",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="Numéro de téléphone de la mairie",
            ),
        ),
    ]
