# Generated by Django 3.1.6 on 2021-02-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0018_elus_epci"),
    ]

    operations = [
        migrations.AddField(
            model_name="elumunicipal",
            name="ordre_fonction",
            field=models.PositiveSmallIntegerField(
                editable=False, null=True, verbose_name="Ordre de la fonction"
            ),
        ),
        migrations.AlterField(
            model_name="elumunicipal",
            name="fonction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAI", "Maire"),
                    ("MDA", "Maire délégué⋅e"),
                    ("VPE", "Vice-Président⋅e"),
                    ("PRE", "Président⋅e"),
                    ("ADJ", "Adjoint⋅e au maire"),
                    ("AMC", "Autre membre de la commission permanente"),
                ],
                editable=False,
                max_length=50,
                verbose_name="Fonction",
            ),
        ),
    ]
