# Generated by Django 3.1.7 on 2021-05-28 07:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0020_elumunicipal_parrainage2017"),
    ]

    operations = [
        migrations.CreateModel(
            name="CirconscriptionConsulaire",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        editable=False,
                        max_length=300,
                        verbose_name="Nom de la circonscription",
                    ),
                ),
                (
                    "consulats",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        editable=False,
                        size=None,
                        verbose_name="Consulats inclus",
                    ),
                ),
                (
                    "nombre_conseillers",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="Nombre de conseillers"
                    ),
                ),
                (
                    "search",
                    django.contrib.postgres.search.SearchVectorField(
                        verbose_name="Champ de recherche", null=True
                    ),
                ),
            ],
            options={"verbose_name_plural": "circonscriptions consulaires"},
        ),
        migrations.AddIndex(
            model_name="circonscriptionconsulaire",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search"], name="data_france_search_24673a_gin"
            ),
        ),
    ]
