# Generated by Django 3.1.7 on 2021-07-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0028_eluregional"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeputeEuropeen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        editable=False, max_length=200, verbose_name="Nom de famille"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        verbose_name="Prénom",
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Feminin")],
                        max_length=1,
                        verbose_name="Sexe à l'état civil",
                    ),
                ),
                (
                    "date_naissance",
                    models.DateField(editable=False, verbose_name="Date de naissance"),
                ),
                (
                    "profession",
                    models.SmallIntegerField(
                        editable=False, null=True, verbose_name="Profession"
                    ),
                ),
                (
                    "date_debut_mandat",
                    models.DateField(
                        editable=False, verbose_name="Date de début du mandat"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "Député‧e européen‧ne",
                "verbose_name": "Député‧es européen‧es",
                "ordering": ("nom", "prenom", "date_naissance"),
            },
        ),
        migrations.AlterModelOptions(
            name="eludepartemental",
            options={
                "ordering": ("canton", "nom", "prenom", "date_naissance"),
                "verbose_name": "Élu‧e départemental‧e",
                "verbose_name_plural": "Élu‧es départementaux‧ales",
            },
        ),
        migrations.AlterModelOptions(
            name="eluregional",
            options={
                "ordering": ("region", "nom", "prenom", "date_naissance"),
                "verbose_name": "Élu‧e régional‧e",
                "verbose_name_plural": "Élu‧es régionaux‧ales",
            },
        ),
    ]
