# Generated by Django 4.1.5 on 2023-01-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0033_circonscriptionconsulaire_pays"),
    ]

    operations = [
        migrations.AddField(
            model_name="depute",
            name="actif",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="Mandat en cours"
            ),
        ),
        migrations.AddField(
            model_name="deputeeuropeen",
            name="actif",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="Mandat en cours"
            ),
        ),
        migrations.AddField(
            model_name="eludepartemental",
            name="actif",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="Mandat en cours"
            ),
        ),
        migrations.AddField(
            model_name="elumunicipal",
            name="actif",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="Mandat en cours"
            ),
        ),
        migrations.AddField(
            model_name="eluregional",
            name="actif",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="Mandat en cours"
            ),
        ),
        migrations.AlterField(
            model_name="eludepartemental",
            name="date_debut_fonction",
            field=models.DateField(
                editable=False, null=True, verbose_name="Date de début de la fonction"
            ),
        ),
        migrations.AlterField(
            model_name="elumunicipal",
            name="date_debut_fonction",
            field=models.DateField(
                editable=False, null=True, verbose_name="Date de début de la fonction"
            ),
        ),
        migrations.AlterField(
            model_name="eluregional",
            name="date_debut_fonction",
            field=models.DateField(
                editable=False, null=True, verbose_name="Date de début de la fonction"
            ),
        ),
    ]
