# Generated by Django 4.1.5 on 2023-02-03 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_france", "0035_changer_lien_conseiller_regionaux"),
    ]

    operations = [
        migrations.AddField(
            model_name="circonscriptionconsulaire",
            name="circonscription_legislative",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_france.circonscriptionlegislative",
                verbose_name="Circonscription législative",
                related_name="+",
            ),
        ),
    ]
