# Generated by Django 4.1.6 on 2023-02-03 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_france", "0036_circonscriptionconsulaire_circonscription_legislative"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deputeeuropeen",
            options={
                "ordering": ("nom", "prenom", "date_naissance"),
                "verbose_name": "Député‧e européen‧ne",
                "verbose_name_plural": "Député·es européen·nes",
            },
        ),
    ]
