# Generated by Django 5.2.17 on 2026-10-05 14:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_france", "0037_alter_deputeeuropeen_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depute",
            name="relation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "Président⋅e de groupe"),
                    ("M", "Membre"),
                    ("A", "Membre apparenté au groupe"),
                    ("R", "Rattaché⋅e administrativement au groupe"),
                ],
                editable=False,
                max_length=1,
                verbose_name="Appartenance au groupe",
            ),
        ),
        migrations.CreateModel(
            name="Senateur",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        editable=False, max_length=200, verbose_name="Nom de famille"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        verbose_name="Prénom",
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Feminin")],
                        max_length=1,
                        verbose_name="Sexe à l'état civil",
                    ),
                ),
                (
                    "date_naissance",
                    models.DateField(editable=False, verbose_name="Date de naissance"),
                ),
                (
                    "profession",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Agriculteurs exploitants"),
                            (10, "Agriculteurs exploitants"),
                            (11, "Agriculteurs sur petite exploitation"),
                            (12, "Agriculteurs sur moyenne exploitation"),
                            (13, "Agriculteurs sur grande exploitation"),
                            (2, "Artisans, commerçants et chefs d'entreprise"),
                            (21, "Artisans"),
                            (22, "Commerçants et assimilés"),
                            (23, "Chefs d'entreprise de 10 salariés ou plus"),
                            (3, "Cadres et professions intellectuelles supérieures"),
                            (31, "Professions libérales et assimilés"),
                            (
                                32,
                                "Cadres de la fonction publique, professions intellectuelles et  artistiques",
                            ),
                            (33, "Cadres de la fonction publique"),
                            (34, "Professeurs, professions scientifiques"),
                            (
                                35,
                                "Professions de l'information, des arts et des spectacles",
                            ),
                            (36, "Cadres d'entreprise"),
                            (37, "Cadres administratifs et commerciaux d'entreprise"),
                            (38, "Ingénieurs et cadres techniques d'entreprise"),
                            (4, "Professions Intermédiaires"),
                            (
                                41,
                                "Professions intermédiaires de l'enseignement, de la santé, de la fonction publique et assimilés",
                            ),
                            (42, "Professeurs des écoles, instituteurs et assimilés"),
                            (
                                43,
                                "Professions intermédiaires de la santé et  du travail social",
                            ),
                            (44, "Clergé, religieux"),
                            (
                                45,
                                "Professions intermédiaires administratives de la fonction publique",
                            ),
                            (
                                46,
                                "Professions intermédiaires administratives et commerciales des entreprises",
                            ),
                            (47, "Techniciens"),
                            (48, "Contremaîtres, agents de maîtrise"),
                            (5, "Employés"),
                            (51, "Employés de la fonction publique"),
                            (
                                52,
                                "Employés civils et agents de service de la fonction publique",
                            ),
                            (53, "Policiers et militaires"),
                            (54, "Employés administratifs d'entreprise"),
                            (55, "Employés de commerce"),
                            (56, "Personnels des services directs aux particuliers"),
                            (6, "Ouvriers"),
                            (61, "Ouvriers qualifiés"),
                            (62, "Ouvriers qualifiés de type industriel"),
                            (63, "Ouvriers qualifiés de type artisanal"),
                            (64, "Chauffeurs"),
                            (
                                65,
                                "Ouvriers qualifiés de la manutention, du magasinage et du transport",
                            ),
                            (66, "Ouvriers non qualifiés"),
                            (67, "Ouvriers non qualifiés de type industriel"),
                            (68, "Ouvriers non qualifiés de type artisanal"),
                            (69, "Ouvriers agricoles"),
                            (7, "Retraités"),
                            (71, "Anciens agriculteurs exploitants"),
                            (72, "Anciens artisans, commerçants, chefs d'entreprise"),
                            (73, "Anciens cadres et professions intermédiaires"),
                            (74, "Anciens cadres"),
                            (75, "Anciennes professions intermédiaires"),
                            (76, "Anciens employés et ouvriers"),
                            (77, "Anciens employés"),
                            (78, "Anciens ouvriers"),
                            (8, "Autres personnes sans activité professionnelle"),
                            (81, "Chômeurs n'ayant jamais travaillé"),
                            (82, "Inactifs divers (autres que retraités)"),
                            (83, "Militaires du contingent"),
                            (84, "Elèves, étudiants"),
                            (
                                85,
                                "Personnes diverses sans activité  professionnelle de moins de 60 ans (sauf retraités)",
                            ),
                            (
                                86,
                                "Personnes diverses sans activité professionnelle de 60 ans et plus (sauf retraités)",
                            ),
                        ],
                        editable=False,
                        null=True,
                        verbose_name="Profession",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False, max_length=10, verbose_name="Matricule Sénat"
                    ),
                ),
                (
                    "circonscription",
                    models.CharField(
                        editable=False,
                        help_text="Code du département ou de la collectivité d'outremer, 99 pour les Français établis hors de France",
                        max_length=3,
                        verbose_name="Code de la circonscription",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="Mandat en cours"
                    ),
                ),
                (
                    "groupe",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        verbose_name="Groupe politique",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "Président⋅e de groupe"),
                            ("M", "Membre"),
                            ("A", "Membre apparenté au groupe"),
                            ("R", "Rattaché⋅e administrativement au groupe"),
                        ],
                        editable=False,
                        max_length=1,
                        verbose_name="Appartenance au groupe",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        editable=False,
                        max_length=254,
                        verbose_name="Adresse email",
                    ),
                ),
                (
                    "description_profession",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=500,
                        verbose_name="Description de la profession",
                    ),
                ),
                (
                    "date_debut_mandat",
                    models.DateField(
                        editable=False,
                        null=True,
                        verbose_name="Date de début du mandat",
                    ),
                ),
                (
                    "search",
                    django.contrib.postgres.search.SearchVectorField(
                        null=True, verbose_name="Champ de recherche"
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senateurs",
                        related_query_name="senateur",
                        to="data_france.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sénateur‧ice",
                "verbose_name_plural": "Sénateur‧ices",
                "ordering": ("nom", "prenom", "date_naissance"),
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search"], name="data_france_search_ff9257_gin"
                    )
                ],
            },
        ),
    ]
